#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

DIRS = [
    "config",
    "data/raw",
    "data/processed",
    "src/data",
    "src/features",
    "src/labels",
    "src/models",
    "src/backtest",
    "src/utils",
    "notebooks",
    "runs",
]

FILES = {
    "README.md": "# Trading Bot Plan v1\n\nGenerated by bootstrap_project.py\n",
    "requirements.txt": "",
    "config/symbols.yaml": "symbols:\n  - BTCUSDT\n  - ETHUSDT\n",
    "config/backtest.yaml": (
        "timeframe: 15m\n"
        "max_holding_hours: 6\n"
        "labeling:\n"
        "  tp_atr_mult: 1.2\n"
        "  sl_atr_mult: 1.0\n"
        "  horizon_candles: 24\n"
        "costs:\n"
        "  taker_fee_bps: 6\n"
        "  slippage_bps_major: 3\n"
        "  slippage_bps_alt: 5\n"
        "risk:\n"
        "  risk_per_trade_pct: 1.0\n"
        "  daily_stop_r: 3\n"
    ),
    "src/__init__.py": "",
    "src/data/__init__.py": "",
    "src/features/__init__.py": "",
    "src/labels/__init__.py": "",
    "src/models/__init__.py": "",
    "src/backtest/__init__.py": "",
    "src/utils/__init__.py": "",
    "src/data/fetch_bitget.py": '"""Fetch 15m OHLCV from Bitget and write to data/raw."""\n',
    "src/data/fetch_binance.py": '"""Fetch 15m OHLCV from Binance (long history) and write to data/raw."""\n',
    "src/data/store.py": '"""Parquet storage utilities + integrity checks (gaps/dupes)."""\n',
    "src/features/build_features.py": '"""Build causal features and cache to data/processed/features."""\n',
    "src/labels/triple_barrier.py": '"""Triple-barrier labeling (cost-aware) and cache to data/processed/labels."""\n',
    "src/models/train_baseline.py": '"""Train baseline model (e.g., LightGBM/XGBoost) with walk-forward splits."""\n',
    "src/models/train_sequence.py": '"""Train sequence model (CNN/LSTM) - optional after baselines."""\n',
    "src/models/predict.py": '"""Load model + produce signals (long/short/no-trade) with gating threshold."""\n',
    "src/backtest/engine.py": '"""Backtest engine: next-open entries, intrabar SL/TP, costs, risk rules."""\n',
    "src/backtest/costs.py": '"""Fee + slippage models."""\n',
    "src/backtest/risk.py": '"""Position sizing (fixed risk per trade) + daily stop logic."""\n',
    "src/utils/time.py": '"""Time utilities: candle alignment, UTC conversions, interval checks."""\n',
    "src/utils/io.py": '"""I/O helpers: config loading, path helpers, hashing configs."""\n',
}


def write_file(path: Path, content: str, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".", help="Project root directory")
    ap.add_argument("--overwrite", action="store_true", help="Overwrite existing files")
    args = ap.parse_args()

    root = Path(args.root).resolve()

    for d in DIRS:
        (root / d).mkdir(parents=True, exist_ok=True)

    for rel, content in FILES.items():
        write_file(root / rel, content, overwrite=args.overwrite)

    print(f"✅ Created/verified structure under: {root}")


if __name__ == "__main__":
    main()
